# Genome
referenceGenome: ""

# Paths
fastq_directory: "/path/to/input/dir"
outputPath: "/path/to/output/dir" # Dont't include the trailing "/"
allPrefix: "test"

# Parameters
threads: 16
minimumReadSupport: 3
insertionDistanceLimitIntraPatient: 20
insertionDistanceLimitInterPatient: 20
survivorInsertionDistanceLimitIntraPatient: 10
survivorInsertionDistanceLimitInterPatient: 500
enrichmentSignificanceThreshold: 0.01
datasets: ["indigen"]

# Keep certain files
keepRds: True

samples: {}

comparisons:
  [
   ['NA19240', 'HG00514'],
  ]
