# Genome
referenceGenome: ""
species: "homo_sapiens"

# Paths
fastq_directory: "./"
outputPath: "./" # Dont't include the trailing "/"
allPrefix: "template"

# Parameters
threads: 32
mode: "full"
minimumReadSupport: 3
insertionDistanceLimitIntraPatient: 60
insertionDistanceLimitInterPatient: 60
survivorInsertionDistanceLimitIntraPatient: 60
survivorInsertionDistanceLimitInterPatient: 100
enrichmentSignificanceThreshold: 0.05
callers: ["cuteSV", "sniffles2"]
datasets: []

# Keep certain files
keepRds: True

samples: {}

comparisons: []
